apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Application workloads managed by Argo CD

  sourceRepos:
    - "https://github.com/rishindrasingh/rishindra-gitops.git"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: easyshop
    - server: https://kubernetes.default.svc
      namespace: bankapp
    - server: https://kubernetes.default.svc
      namespace: chatapp

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: storage.k8s.io
    kind: StorageClass