apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd

spec:
  description: Infrastructure and platform components

  sourceRepos:
    - "https://github.com/rishindrasingh/rishindra-gitops.git"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"