# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
#   namespace: easyshop
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: easyshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-gp3
  resources:
    requests:
      storage: 5Gi