apiVersion: v1
kind: Secret
metadata:
  name: rishindra-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rishindrasingh/rishindra-gitops.git
  username: rishindrasingh23@gmail.com
  password: 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